"""Schema exports."""

from schemas.auth import (
    AuthResponse,
    LoginRequest,
    MessageResponse,
    PasswordResetRequest,
    PasswordUpdateRequest,
    RegisterRequest,
    UserResponse,
)
from schemas.plans import (
    CoachRosterResponse,
    PaginatedPlansResponse,
    PlanAssignRequest,
    PlanAssignResponse,
    PlanCreateRequest,
    PlanDetailResponse,
    PlanListItemResponse,
    PlanListQuery,
    PlanUpdateRequest,
    PlanUsersResponse,
)
from schemas.users import (
    AdminOverviewResponse,
    CoachAssignmentRequest,
    CoachAssignmentResponse,
    CoachSummaryResponse,
    PaginatedUsersResponse,
    UserCreateRequest,
    UserDetailResponse,
    UserListItemResponse,
    UserListQuery,
    UserUpdateRequest,
)
from schemas.workouts import (
    CardioTypeResponse,
    MuscleGroupCreateRequest,
    MuscleGroupResponse,
    PaginatedWorkoutsResponse,
    WorkoutArchiveResponse,
    WorkoutCreateRequest,
    WorkoutListQuery,
)
from schemas.workouts import WorkoutResponse as WorkoutLibraryResponse
from schemas.workouts import (
    WorkoutUpdateRequest,
)

__all__ = [
    "AuthResponse",
    "LoginRequest",
    "MessageResponse",
    "PasswordResetRequest",
    "PasswordUpdateRequest",
    "RegisterRequest",
    "UserResponse",
    "UserCreateRequest",
    "UserUpdateRequest",
    "UserListQuery",
    "UserListItemResponse",
    "PaginatedUsersResponse",
    "UserDetailResponse",
    "CoachSummaryResponse",
    "CoachAssignmentRequest",
    "CoachAssignmentResponse",
    "AdminOverviewResponse",
    "WorkoutLibraryResponse",
    "WorkoutCreateRequest",
    "WorkoutUpdateRequest",
    "WorkoutListQuery",
    "PaginatedWorkoutsResponse",
    "WorkoutArchiveResponse",
    "MuscleGroupResponse",
    "MuscleGroupCreateRequest",
    "CardioTypeResponse",
    "PlanListQuery",
    "PlanListItemResponse",
    "PaginatedPlansResponse",
    "PlanDetailResponse",
    "PlanCreateRequest",
    "PlanUpdateRequest",
    "PlanAssignRequest",
    "PlanAssignResponse",
    "PlanUsersResponse",
    "CoachRosterResponse",
]
