"""Schema exports."""

from schemas.auth import (
    AuthResponse,
    LoginRequest,
    MessageResponse,
    PasswordResetRequest,
    PasswordUpdateRequest,
    RegisterRequest,
    UserResponse,
)
from schemas.dashboard import (
    UserCoachResponse,
    UserCoachesResponse,
    UserQuickStatsResponse,
    UserTodayWorkoutResponse,
    UserWeekPlanDayResponse,
    UserWeekPlanResponse,
)
from schemas.import_export import CSVImportErrorItem, CSVImportResponse
from schemas.plan_activation import (
    ActivePlanSummaryResponse,
    PendingPlanAssignmentResponse,
    PlanAssignmentActionResponse,
    UserPendingPlansResponse,
)
from schemas.plans import (
    CoachRosterResponse,
    PaginatedPlansResponse,
    PlanAssignRequest,
    PlanAssignResponse,
    PlanCreateRequest,
    PlanDetailResponse,
    PlanListItemResponse,
    PlanListQuery,
    PlanUpdateRequest,
    PlanUsersResponse,
)
from schemas.progress import (
    FrequencyBucketResponse,
    FrequencyProgressQuery,
    FrequencyProgressResponse,
    MuscleGroupProgressItemResponse,
    MuscleGroupProgressResponse,
    PaginatedUserSessionsResponse,
    ProgressDateRangeQuery,
    SessionHistoryItemResponse,
    SessionHistoryLogResponse,
    UserSessionHistoryQuery,
)
from schemas.sessions import (
    SessionCreateRequest,
    SessionLogCreateRequest,
    SessionLogInput,
    SessionLogResponse,
    SessionLogUpdateRequest,
    SessionResponse,
    SessionUpdateRequest,
)
from schemas.users import (
    AdminOverviewResponse,
    CoachAssignmentRequest,
    CoachAssignmentResponse,
    CoachSummaryResponse,
    PaginatedUsersResponse,
    UserCreateRequest,
    UserDetailResponse,
    UserListItemResponse,
    UserListQuery,
    UserUpdateRequest,
)
from schemas.workouts import (
    CardioTypeResponse,
    MuscleGroupCreateRequest,
    MuscleGroupResponse,
    PaginatedWorkoutsResponse,
    WorkoutArchiveResponse,
    WorkoutCreateRequest,
    WorkoutListQuery,
)
from schemas.workouts import WorkoutResponse as WorkoutLibraryResponse
from schemas.workouts import (
    WorkoutUpdateRequest,
)

__all__ = [
    "AuthResponse",
    "LoginRequest",
    "MessageResponse",
    "PasswordResetRequest",
    "PasswordUpdateRequest",
    "RegisterRequest",
    "UserResponse",
    "UserCreateRequest",
    "UserUpdateRequest",
    "UserListQuery",
    "UserListItemResponse",
    "PaginatedUsersResponse",
    "UserDetailResponse",
    "CoachSummaryResponse",
    "CoachAssignmentRequest",
    "CoachAssignmentResponse",
    "AdminOverviewResponse",
    "WorkoutLibraryResponse",
    "WorkoutCreateRequest",
    "WorkoutUpdateRequest",
    "WorkoutListQuery",
    "PaginatedWorkoutsResponse",
    "WorkoutArchiveResponse",
    "MuscleGroupResponse",
    "MuscleGroupCreateRequest",
    "CardioTypeResponse",
    "PlanListQuery",
    "PlanListItemResponse",
    "PaginatedPlansResponse",
    "PlanDetailResponse",
    "PlanCreateRequest",
    "PlanUpdateRequest",
    "PlanAssignRequest",
    "PlanAssignResponse",
    "PlanUsersResponse",
    "CoachRosterResponse",
    "UserTodayWorkoutResponse",
    "UserWeekPlanDayResponse",
    "UserWeekPlanResponse",
    "UserQuickStatsResponse",
    "UserCoachResponse",
    "UserCoachesResponse",
    "ActivePlanSummaryResponse",
    "PendingPlanAssignmentResponse",
    "UserPendingPlansResponse",
    "PlanAssignmentActionResponse",
    "CSVImportErrorItem",
    "CSVImportResponse",
    "SessionLogInput",
    "SessionLogCreateRequest",
    "SessionLogUpdateRequest",
    "SessionCreateRequest",
    "SessionUpdateRequest",
    "SessionLogResponse",
    "SessionResponse",
    "UserSessionHistoryQuery",
    "SessionHistoryLogResponse",
    "SessionHistoryItemResponse",
    "PaginatedUserSessionsResponse",
    "ProgressDateRangeQuery",
    "MuscleGroupProgressItemResponse",
    "MuscleGroupProgressResponse",
    "FrequencyProgressQuery",
    "FrequencyBucketResponse",
    "FrequencyProgressResponse",
]
